In [1]:
# set: doesn't like repetition 
# list:inclusive and mutable     
# tuple: unmutable

In [2]:
#in finance sector, you don't want to give access to all units that who can change the sensitive info so you can define your variables as tuples.

In [4]:
for i in [3,5,7]:
    a = i*i
    print(a) 

9
25
49



# Data Manipulaion 

In [ ]:
#LIST     > ARRAY > DF
#ORG(CORE)> NUMPY > PANDAS

In [21]:
import numpy as np  #Numerical Python...>Numpy

#in array all data should be same than this make memory optimization and increases performance in some cases.
# performance difference,difference in size and shape operations, a function difference, in this case depending on the performance difference


In [9]:
[10,20,30]+[5,10,15]

[10, 20, 30, 5, 10, 15]

In [6]:
#lets make our list to array

In [7]:
np.array([10,20,30])+np.array([5,10,15])

array([15, 30, 45])

In [10]:
# now we can sum of these arrays

In [11]:
#lets make filter in numpy array

In [12]:
a_array = np.array([1,2,3,4,5,6,7,8,9,1,0,15,25,42,53,8,69,69,75,25,27,85,65,35,66,11,22,35])

In [17]:
a_array<20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
       False])

In [ ]:
#i want list of the elements which is less than 20

In [15]:
a_array[[ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
       False]] 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  0, 15,  8, 11])

In [18]:
(a_array<15 | a_array>25)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
def i_learn_for(a,b,c):
    a = b*c

SyntaxError: expected ':' (3048424572.py, line 1)

# Data Frame

In [177]:
my_list = [1,2,3]

for i in my_list:
    print(i)

1
2
3


In [32]:
import pandas as pd

In [25]:
#give me 3 features for data frames
#1-index/a adress number
#2-column
#3-value

In [29]:
arr= np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
#array([[1, 2, 3],
     #  [4, 5, 6],
     #  [7, 8, 9]])
#here rows are arrays !

In [33]:
df = pd.DataFrame(arr,columns = ["Age", "Gender", "Income"])  #here we changed the columns

In [34]:
df.index = ["Sally", "Emma", "Eva"]

In [35]:
df

Age  Gender  Income
Sally    1       2       3
Emma     4       5       6
Eva      7       8       9

In [178]:
df[(df.index>30)]

survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
31          1       1  female   NaN      1      0  146.5208        C   First   
32          1       3  female   NaN      0      0    7.7500        Q   Third   
33          0       2    male  66.0      0      0   10.5000        S  Second   
34          0       1    male  28.0      1      0   82.1708        C   First   
35          0       1    male  42.0      1      0   52.0000        S   First   
..        ...     ...     ...   ...    ...    ...       ...      ...     ...   
886         0       2    male  27.0      0      0   13.0000        S  Second   
887         1       1  female  19.0      0      0   30.0000        S   First   
888         0       3  female   NaN      1      2   23.4500        S   Third   
889         1       1    male  26.0      0      0   30.0000        C   First   
890         0       3    male  32.0      0      0    7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
31   woman       False    B    Cherbourg   yes  False  
32   woman       False  NaN   Queenstown   yes   True  
33     man        True  NaN  Southampton    no   True  
34     man        True  NaN    Cherbourg    no  False  
35     man        True  NaN  Southampton    no  False  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[860 rows x 15 columns]

In [44]:
#seaborn database list

In [51]:
import seaborn as sns

In [54]:
sns.load_dataset("titanic")

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [72]:
df = sns.load_dataset("titanic")

In [73]:
df = df.copy()

In [ ]:
#When start to analyze, look at shape, head, values of data

In [76]:
df.shape 

(891, 15)

In [78]:
891*15   #too much data

13365

In [79]:
#Analysis

#We should filter some of the columns  (filter....select)

In [82]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [85]:
columns_selected = ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone']

In [93]:
df_subdata = df [columns_selected]   #creating useless df could be load for storage

In [90]:
#filter

In [99]:
my_filter = (df_subdata["who"]=="woman") & (df_subdata["class"]=="First")

In [103]:
df_subdata = df_subdata [my_filter]  #we want to return sub_data

df_subdata  

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1           1       1  female  38.0      1      0   71.2833        C  First   
3           1       1  female  35.0      1      0   53.1000        S  First   
11          1       1  female  58.0      0      0   26.5500        S  First   
31          1       1  female   NaN      1      0  146.5208        C  First   
52          1       1  female  49.0      1      0   76.7292        C  First   
..        ...     ...     ...   ...    ...    ...       ...      ...    ...   
856         1       1  female  45.0      1      1  164.8667        S  First   
862         1       1  female  48.0      0      0   25.9292        S  First   
871         1       1  female  47.0      1      1   52.5542        S  First   
879         1       1  female  56.0      0      1   83.1583        C  First   
887         1       1  female  19.0      0      0   30.0000        S  First   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
3    woman       False    C  Southampton   yes  False  
11   woman       False    C  Southampton   yes   True  
31   woman       False    B    Cherbourg   yes  False  
52   woman       False    D    Cherbourg   yes  False  
..     ...         ...  ...          ...   ...    ...  
856  woman       False  NaN  Southampton   yes  False  
862  woman       False    D  Southampton   yes   True  
871  woman       False    D  Southampton   yes  False  
879  woman       False    C    Cherbourg   yes  False  
887  woman       False    B  Southampton   yes   True  

[91 rows x 15 columns]

In [104]:
# df_subdata.index<50

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [180]:
df_subdata[(df_subdata.index<50)].head

<bound method NDFrame.head of     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1          1       1  female  38.0      1      0   71.2833        C  First   
3          1       1  female  35.0      1      0   53.1000        S  First   
11         1       1  female  58.0      0      0   26.5500        S  First   
31         1       1  female   NaN      1      0  146.5208        C  First   

      who  adult_male deck  embark_town alive  alone  
1   woman       False    C    Cherbourg   yes  False  
3   woman       False    C  Southampton   yes  False  
11  woman       False    C  Southampton   yes   True  
31  woman       False    B    Cherbourg   yes  False  >

In [84]:
df.index #these are rows

RangeIndex(start=0, stop=891, step=1)

In [67]:
df.head()  #we look from top to bottom

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [68]:
df.tail()  #we look from bottom to top

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [64]:
df.values

array([[0, 3, 'male', ..., 'Southampton', 'no', False],
       [1, 1, 'female', ..., 'Cherbourg', 'yes', False],
       [1, 3, 'female', ..., 'Southampton', 'yes', True],
       ...,
       [0, 3, 'female', ..., 'Southampton', 'no', False],
       [1, 1, 'male', ..., 'Cherbourg', 'yes', True],
       [0, 3, 'male', ..., 'Queenstown', 'no', True]], dtype=object)

In [66]:
for i in df.values:
    print(i)           #we get all data

[0 3 'male' 22.0 1 0 7.25 'S' 'Third' 'man' True nan 'Southampton' 'no'
 False]
[1 1 'female' 38.0 1 0 71.2833 'C' 'First' 'woman' False 'C' 'Cherbourg'
 'yes' False]
[1 3 'female' 26.0 0 0 7.925 'S' 'Third' 'woman' False nan 'Southampton'
 'yes' True]
[1 1 'female' 35.0 1 0 53.1 'S' 'First' 'woman' False 'C' 'Southampton'
 'yes' False]
[0 3 'male' 35.0 0 0 8.05 'S' 'Third' 'man' True nan 'Southampton' 'no'
 True]
[0 3 'male' nan 0 0 8.4583 'Q' 'Third' 'man' True nan 'Queenstown' 'no'
 True]
[0 1 'male' 54.0 0 0 51.8625 'S' 'First' 'man' True 'E' 'Southampton' 'no'
 True]
[0 3 'male' 2.0 3 1 21.075 'S' 'Third' 'child' False nan 'Southampton'
 'no' False]
[1 3 'female' 27.0 0 2 11.1333 'S' 'Third' 'woman' False nan 'Southampton'
 'yes' False]
[1 2 'female' 14.0 1 0 30.0708 'C' 'Second' 'child' False nan 'Cherbourg'
 'yes' False]
[1 3 'female' 4.0 1 1 16.7 'S' 'Third' 'child' False 'G' 'Southampton'
 'yes' False]
[1 1 'female' 58.0 0 0 26.55 'S' 'First' 'woman' False 'C' 'Southampton'
 '

In [70]:
df[df["survived"]==1]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
8           1       3  female  27.0      0      2  11.1333        S   Third   
9           1       2  female  14.0      1      0  30.0708        C  Second   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
875         1       3  female  15.0      0      0   7.2250        C   Third   
879         1       1  female  56.0      0      1  83.1583        C   First   
880         1       2  female  25.0      0      1  26.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
889         1       1    male  26.0      0      0  30.0000        C   First   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
8    woman       False  NaN  Southampton   yes  False  
9    child       False  NaN    Cherbourg   yes  False  
..     ...         ...  ...          ...   ...    ...  
875  child       False  NaN    Cherbourg   yes   True  
879  woman       False    C    Cherbourg   yes  False  
880  woman       False  NaN  Southampton   yes  False  
887  woman       False    B  Southampton   yes   True  
889    man        True    C    Cherbourg   yes   True  

[342 rows x 15 columns]

In [71]:
import warnings

warnings.filterwarnings("ignore")  #I don't like warnings:)

#!pip install kutuphane 

In [61]:
df[(df["survived"]==1) & (df["who"]=="woman")][["who"]]

who
1    woman
2    woman
3    woman
8    woman
11   woman
..     ...
871  woman
874  woman
879  woman
880  woman
887  woman

[205 rows x 1 columns]

In [ ]:
#always columns come as a list

In [181]:
df[df["survived"]==1]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
8           1       3  female  27.0      0      2  11.1333        S   Third   
9           1       2  female  14.0      1      0  30.0708        C  Second   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
875         1       3  female  15.0      0      0   7.2250        C   Third   
879         1       1  female  56.0      0      1  83.1583        C   First   
880         1       2  female  25.0      0      1  26.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
889         1       1    male  26.0      0      0  30.0000        C   First   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
8    woman       False  NaN  Southampton   yes  False  
9    child       False  NaN    Cherbourg   yes  False  
..     ...         ...  ...          ...   ...    ...  
875  child       False  NaN    Cherbourg   yes   True  
879  woman       False    C    Cherbourg   yes  False  
880  woman       False  NaN  Southampton   yes  False  
887  woman       False    B  Southampton   yes   True  
889    man        True    C    Cherbourg   yes   True  

[342 rows x 15 columns]

In [111]:
df.groupby("sex").agg({"fare":"mean"})

fare
sex              
female  44.479818
male    25.523893

In [114]:
df.groupby("who").agg({"age":["count","mean","max","min"]})

age                        
      count       mean   max    min
who                                
child    83   6.369518  15.0   0.42
man     413  33.173123  80.0  16.00
woman   218  32.000000  63.0  16.00

In [117]:
df.groupby(["who","class"]).agg({"fare":["mean","count"]})

fare      
                    mean count
who   class                   
child First   139.382633     6
      Second   28.323905    19
      Third    23.220190    58
man   First    65.951086   119
      Second   19.054124    99
      Third    11.340213   319
woman First   104.317995    91
      Second   20.868624    66
      Third    15.354351   114

In [122]:
df.groupby(["who","class"]).agg({"fare":["mean"], "survived" : ["mean"] }).reset_index()   #piwot table classic view

who   class        fare  survived
                        mean      mean
0  child   First  139.382633  0.833333
1  child  Second   28.323905  1.000000
2  child   Third   23.220190  0.431034
3    man   First   65.951086  0.352941
4    man  Second   19.054124  0.080808
5    man   Third   11.340213  0.119122
6  woman   First  104.317995  0.978022
7  woman  Second   20.868624  0.909091
8  woman   Third   15.354351  0.491228

In [123]:
#dictionary  agg function ( {"purpose":"result"}  , {"key":"value"} )

In [125]:
df.iloc[[0,5]]  #row selection

survived  pclass   sex   age  sibsp  parch    fare embarked  class  who  \
0         0       3  male  22.0      1      0  7.2500        S  Third  man   
5         0       3  male   NaN      0      0  8.4583        Q  Third  man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
5        True  NaN   Queenstown    no   True

In [131]:
df.iloc[0:100][["fare","class"]]

fare   class
0    7.2500   Third
1   71.2833   First
2    7.9250   Third
3   53.1000   First
4    8.0500   Third
..      ...     ...
95   8.0500   Third
96  34.6542   First
97  63.3583   First
98  23.0000  Second
99  26.0000  Second

[100 rows x 2 columns]

In [132]:
pd.crosstab(df["sex"],df["embark_town"])

embark_town  Cherbourg  Queenstown  Southampton
sex                                            
female              73          36          203
male                95          41          441

In [133]:
df.iloc[15, 0:10] 

survived         1
pclass           2
sex         female
age           55.0
sibsp            0
parch            0
fare          16.0
embarked         S
class       Second
who          woman
Name: 15, dtype: object

In [135]:
df["fare"]<3

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: fare, Length: 891, dtype: bool

In [137]:
df.isnull()  

survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0       False   False  False  False  False  False  False     False  False   
1       False   False  False  False  False  False  False     False  False   
2       False   False  False  False  False  False  False     False  False   
3       False   False  False  False  False  False  False     False  False   
4       False   False  False  False  False  False  False     False  False   
..        ...     ...    ...    ...    ...    ...    ...       ...    ...   
886     False   False  False  False  False  False  False     False  False   
887     False   False  False  False  False  False  False     False  False   
888     False   False  False   True  False  False  False     False  False   
889     False   False  False  False  False  False  False     False  False   
890     False   False  False  False  False  False  False     False  False   

       who  adult_male   deck  embark_town  alive  alone  
0    False       False   True        False  False  False  
1    False       False  False        False  False  False  
2    False       False   True        False  False  False  
3    False       False  False        False  False  False  
4    False       False   True        False  False  False  
..     ...         ...    ...          ...    ...    ...  
886  False       False   True        False  False  False  
887  False       False  False        False  False  False  
888  False       False   True        False  False  False  
889  False       False  False        False  False  False  
890  False       False   True        False  False  False  

[891 rows x 15 columns]

In [141]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [142]:
df.shape[0]  #first element of shape is row shape[row,column]

891

In [139]:
df["age"].sum()

21205.17

In [144]:
df["age"].sum()/df["age"].count()

29.69911764705882

In [145]:
df["embark_town"].value_counts()/df.shape[0]

Southampton    0.722783
Cherbourg      0.188552
Queenstown     0.086420
Name: embark_town, dtype: float64

In [146]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [149]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [150]:
selected_column = ["sex", "embarked", "class", "who", "deck", "embark_town", "alive"]

In [151]:
df_new = df[selected_column]

In [156]:
for col in df_new.columns:
    print ("---")
    print(df[col].value_counts()/df_new.shape[0])

---
male      0.647587
female    0.352413
Name: sex, dtype: float64
---
S    0.722783
C    0.188552
Q    0.086420
Name: embarked, dtype: float64
---
Third     0.551066
First     0.242424
Second    0.206510
Name: class, dtype: float64
---
man      0.602694
woman    0.304153
child    0.093154
Name: who, dtype: float64
---
C    0.066218
B    0.052750
D    0.037037
E    0.035915
A    0.016835
F    0.014590
G    0.004489
Name: deck, dtype: float64
---
Southampton    0.722783
Cherbourg      0.188552
Queenstown     0.086420
Name: embark_town, dtype: float64
---
no     0.616162
yes    0.383838
Name: alive, dtype: float64


In [155]:
def sally :
    

SyntaxError: expected '(' (4115381888.py, line 1)

In [157]:
# df = pd.read_csv(" ", delimiter = ";")  read csv function

FileNotFoundError: [Errno 2] No such file or directory: ' '

In [159]:
df["sex"].count()

891

In [162]:
df["sex"].value_counts()  #we want gender base numbers   the output is series

male      577
female    314
Name: sex, dtype: int64

In [163]:
df.groupby(["sex","embark_town"])

In [174]:
df2 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])     #DIY example
df2

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [176]:
random_arr = np.random.rand(3,3)    #3 by 3 array filled numbers between with random 0 and 1   DIY Example
 

random_arr

array([[0.75507549, 0.11511665, 0.01555894],
       [0.35743227, 0.00817472, 0.11057889],
       [0.453811  , 0.31463659, 0.23801233]])