# Python Ilk Ders
## Temel Kodlar

* Listeler

# Hi All

 * We are learning Python with Jupyter Notebook

## SECTION : INTRO

In [368]:
# The first code

30+3

33

In [3]:
type(5/3)

float

In [4]:
f = 4

In [5]:
type(f)

int

In [7]:
# Step by step

5/3

1.6666666666666667

In [8]:
# Value

3.2

3.2

In [9]:
# Invalid  Variable

type("chrhrhshshthth")

str

In [10]:
'a'

'a'

In [11]:
# Variable

a=3

a

3

In [12]:
9*10

90

In [13]:
# BASE...

In [14]:
a = 9

b = 10

In [15]:
a * b

90

In [16]:
a + b

19

In [17]:
"Python"

'Python'

In [18]:
a= 3
b = "DA Bootcamp"

In [20]:
b.islower() #nokta koyup tab yapiyorum

False

In [21]:
b.lower().islower()

True

In [22]:
type("Python")

str

In [23]:
"Python".upper()

'PYTHON'

In [24]:
len("Python")

6

In [28]:
# len() , print(), islower()

In [31]:
len("Zeliha")

6

In [33]:
print("My favourite color code is:",a)

My favourite color code is: 3


In [34]:
# Fonksiyon
print("Python")

Python


In [35]:
print()

In [36]:
print("En sevdigim sayi : ",3)

En sevdigim sayi :  3


In [37]:
input()

hi


'hi'

In [38]:
a = input()


my name is zeliha


In [39]:
a

'my name is zeliha'

In [40]:
int(a)

ValueError: invalid literal for int() with base 10: 'my name is zeliha'

In [41]:
# Read Data

a = input()

print("Aldigim bilgi : ", a)

sen
Aldigim bilgi :  sen


In [50]:
print("degisken giriniz:")
a = input()
print("degisken giriniz:")
b = input()

a+b

degisken giriniz:
2
degisken giriniz:
2


'22'

In [53]:
x = print ("ali")

ali


In [54]:
type(x)

NoneType

In [55]:
# int() , input()

In [56]:
print("degisken giriniz:")
a =input()
print(type(a))

print("degisken giriniz:")
b =input()
print(type(b))

int(a)+int(b)  # convert , tip donustume, parse ...

3
<class 'str'>
3
<class 'str'>


6

In [57]:
sifre = input()
type(sifre)

1234


str

In [58]:
### Read Data for Calculation

a = int(input())
b = int(input())


print(a*b)

2
2
4


In [59]:
### Read Data for Calculation

a = input()
b = input()

a=int(a)
b=int(b)

print(a+b)

4
4
8


In [60]:
# Methods

type("merhaba")

str

In [61]:
type(3)

int

In [62]:
type(3.4)

float

In [63]:
type(a)

int

In [64]:
type(b)

int

In [65]:
True + True

2

In [66]:
# a = [3,4,5,6,7,-2,5] => [False,False,False,False,False,True,False]

In [67]:
False+False+False+False+False+True+False

1

In [68]:
#DATA >>> Bos hucren var mi...>>> Boslara True, Dolulara False

In [69]:
df.isnull().sum()

NameError: name 'df' is not defined

In [70]:
True+True

2

In [71]:
True+False

1

In [72]:
False+False

0

In [73]:
True-True

0

In [74]:
isnull()

NameError: name 'isnull' is not defined

In [75]:
c= 3.4
type(c)

float

In [79]:
info = "Assignments Operations"

In [80]:
info.lower()

'assignments operations'

In [81]:
type(info)

str

In [82]:
info.capitalize()

'Assignments operations'

In [83]:
info.title()

'Assignments Operations'

In [84]:
info.find("i") # soft dursun...

3

In [85]:
info.split("g")

['Assi', 'nments Operations']

In [86]:
info.count("w")

0

In [87]:
info.endswith("s")

True

In [88]:
info.count("s")

4

In [89]:
info.lower()

'assignments operations'

In [90]:
info = info.upper()

In [91]:
info

'ASSIGNMENTS OPERATIONS'

In [92]:
info.lower()

'assignments operations'

In [93]:
info.lower().replace(" ","|")

'assignments|operations'

In [94]:
info.lower().replace(" ","|").split("|").append(3)

In [98]:
listem = info.lower().replace(" ","|").split("|")

In [99]:
listem

['assignments', 'operations']

In [102]:
listem.append(3)

In [104]:
listem

['assignments', 'operations', 3, 3]

In [109]:
listem.insert(3,1)

In [116]:
listem.insert

<function list.insert(index, object, /)>

In [107]:
listem

['assignments', 'operations', 3, 1, 1, 3]

In [101]:
#listem.insert() tekrar... :)

In [117]:
info.replace(" ","-")

'ASSIGNMENTS-OPERATIONS'

In [118]:
info

'ASSIGNMENTS OPERATIONS'

In [119]:
info.replace(" ", "=")

'ASSIGNMENTS=OPERATIONS'

In [120]:
info = info.replace(" ", "=")

In [121]:
info

'ASSIGNMENTS=OPERATIONS'

In [122]:
info.upper()

'ASSIGNMENTS=OPERATIONS'

In [123]:
info.replace("=", ":")

'ASSIGNMENTS:OPERATIONS'

In [124]:
info = info.upper()

In [125]:
info.replace(" ", "=")

'ASSIGNMENTS=OPERATIONS'

In [126]:
info.replace(" ","|").lower().isupper()

False

In [127]:
info.upper().replace(" ", "=")

'ASSIGNMENTS=OPERATIONS'

In [128]:
a="kirmizi".isupper()+"YOK".isupper()
# a = False + True

In [129]:
a

1

In [130]:
"YESIL".isupper()+"AÇIK".isupper()

2

In [131]:
# Assignments Operations

In [132]:
info = "Assignments Operations"
info

'Assignments Operations'

In [133]:
info.upper()

'ASSIGNMENTS OPERATIONS'

In [134]:
info.lower()

'assignments operations'

In [135]:
info.replace(" ", "=")

'Assignments=Operations'

In [136]:
"ASs".isupper()

False

In [137]:
info.isupper()

False

In [138]:
a = 3
type(3)

int

## SECTION : DATA TYPES

In [139]:
# Data Types & Integer

x = 18
type(x)

int

In [140]:
# Data Types & Integer

y = 4.2
type(y)

float

In [141]:
# Data Types & String

a = "Hello miuul"
type(a)

str

In [142]:
type(a.isupper())

bool

### LIST

In [143]:
a =[3,5]

In [160]:
listem = [2,3,11,"1","q",True]

In [161]:
type(listem)

list

In [162]:
listem[0]

2

In [163]:
listem[5]

True

In [164]:
listem.append(3)

In [165]:
listem

[2, 3, 11, '1', 'q', True, 3]

In [166]:
listem.insert(1,1)

In [167]:
listem

[2, 1, 3, 11, '1', 'q', True, 3]

In [152]:
listem.insert  #<function list.insert(index, object, /)>

<function list.insert(index, object, /)>

In [168]:
listem.insert(1,"a")

In [169]:
listem

[2, 'a', 1, 3, 11, '1', 'q', True, 3]

In [170]:
len(listem)

9

In [171]:
listem.index(1)  # returns what is in the 1st or nd index

2

In [172]:
listem.index  #<function list.index(value, start=0, stop=9223372036854775807, /)>

<function list.index(value, start=0, stop=9223372036854775807, /)>

In [174]:
listem

[2, 'a', 1, 3, 11, '1', 'q', True, 3]

In [179]:
listem = [3,5,8,"Python",True,10]

In [180]:

#[0,1,2,3,4,5]

listem[4:6]  #returns 4th and up to 6th index

[True, 10]

In [181]:
len(listem)

6

In [183]:
listem[len(listem)-1]  #[-x] sign mean always len()-x 

10

In [184]:
listem

[3, 5, 8, 'Python', True, 10]

In [187]:
listem[-4]

8

In [188]:
listem

[3, 5, 8, 'Python', True, 10]

In [189]:
[2, 1, 3, 11, '1', 'q']

[2, 1, 3, 11, '1', 'q']

In [190]:
[2,3.2,True,[3,4,5]]

[2, 3.2, True, [3, 4, 5]]

In [191]:
[2,3.2,True,[3,4,5,[3,4,5]]]

[2, 3.2, True, [3, 4, 5, [3, 4, 5]]]

In [192]:
t= [2,3.2,True,[3,4,5,[3,4,5]]] # ikinci dorde nasil gidilir

In [193]:
t[3][3][1]

4

In [194]:
q= [[2,1,2,10,11],
 [2,1,2,10,11],
 [2,1,2,10,11]]

In [195]:
q[2][-1]

11

In [196]:
listem

[3, 5, 8, 'Python', True, 10]

In [ ]:
#listem = [3,5,8,"Python",True,10]
#array = [3,5,8,3,10]
#array = [2,1,2,10,11]

[[2,1,2,10,11],
 [2,1,2,10,11],
 [2,1,2,10,11]]



#Liste>>>Array>>>DataFrame
#Orj>>>Numpy>>>Pandas +++ Veri Manipulasyonu
#Veri Gorsellestirme ..


In [197]:
my_list = [3,3,4, 'a',True]

#[3,3,4, 'a',True]
#0,1,2,3,4

In [198]:
my_list

[3, 3, 4, 'a', True]

In [199]:
len(my_list)

5

In [200]:
#[3, 3, 4, 'a', True]
#[0, 1, 2,  3,   4]

In [201]:
my_list[3]

'a'

In [202]:
veri = my_list[3]

In [203]:
veri # Listenin. 4. elemani

'a'

In [204]:
my_list[3]='miuul'

In [205]:
my_list

[3, 3, 4, 'miuul', True]

In [206]:
my_list[2]  #2. indeks... 0,1,2,3...

4

In [207]:
my_list[3]

'miuul'

In [208]:
my_list[2:4]

[4, 'miuul']

In [209]:
my_list[3]='miuul'

In [210]:
my_list

[3, 3, 4, 'miuul', True]

## SECTION 3 : LIST is THE BEST

In [211]:
# LIST  >> Array >> Data Frame

In [212]:
# LIST  >> Array >> Data Frame

# ["a",1,[2,3],True]
# [2,3,4,7,10] # lineer cebir
# [2,3,4,7,10] # ddata kolonu (Ismi)

* Practice 1

In [213]:
"miuul"

'miuul'

In [214]:
text = "Once you stop learning, you-start dying."

In [215]:
text.upper().count("O")

4

In [216]:
text.upper()

'ONCE YOU STOP LEARNING, YOU-START DYING.'

In [217]:
text.replace(",", " | ")

'Once you stop learning |  you-start dying.'

In [218]:
text

'Once you stop learning, you-start dying.'

In [219]:
text.split()

['Once', 'you', 'stop', 'learning,', 'you-start', 'dying.']

In [220]:
sp  = text.split()

In [221]:
sp[-1]

'dying.'

In [222]:
sp[0]+" "+sp[1]

'Once you'

In [223]:
text

'Once you stop learning, you-start dying.'

In [224]:
text.upper().replace(",", "$$$$").replace(".", "%%%").split("-")

['ONCE YOU STOP LEARNING$$$$ YOU', 'START DYING%%%']

In [225]:
text.upper().replace(",", "$$$$").replace(".", "%%%").split()

['ONCE', 'YOU', 'STOP', 'LEARNING$$$$', 'YOU-START', 'DYING%%%']

* Practice 2

In [226]:
my_list = ["D","A","T","A"," ","S","C","I","E","N","C","E"]
my_list

['D', 'A', 'T', 'A', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [227]:
len(my_list)

12

In [228]:
for u in my_list:
    print(u+u+u)

DDD
AAA
TTT
AAA
   
SSS
CCC
III
EEE
NNN
CCC
EEE


In [229]:
yeniliste = [2,3,4,7,10]

In [230]:
for G in yeniliste:
    a=G*G
    print(a)

4
9
16
49
100


In [231]:
for G in yeniliste:
    print(G)
    print(G*G)
    print("--------")

2
4
--------
3
9
--------
4
16
--------
7
49
--------
10
100
--------


In [232]:
ekliste = []
yeniliste = [2,3,4,7,10]

In [ ]:
for G in yeniliste:
    ekliste.append(G)
    print(ekliste)

[2]
[2, 3]
[2, 3, 4]
[2, 3, 4, 7]
[2, 3, 4, 7, 10]


In [233]:
# Odev 1
toplam = []
a = [3,5,5,4,11]
b = [2,3,4,7,10] # a ve b'nin toplamini bulunuz

In [234]:
a+b

[3, 5, 5, 4, 11, 2, 3, 4, 7, 10]

In [235]:
# Listenin >> Array

In [236]:
for u in my_list:
    print(u.upper())

D
A
T
A
 
S
C
I
E
N
C
E


In [237]:
my_listB = "DATA SCIENCE"

In [238]:
type(my_listB)

str

In [239]:
len(my_listB)

12

In [240]:
my_list[11]

'E'

In [241]:
my_list[len(my_list)-1]

'E'

In [242]:
my_list[-1]

'E'

In [243]:
my_list[len(my_list)-1]

'E'

In [244]:
my_list[-1]

'E'

In [245]:
my_list[0]

'D'

In [246]:
my_list

['D', 'A', 'T', 'A', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [247]:
my_list[0:4]

['D', 'A', 'T', 'A']

In [248]:
my_list[0:4]+my_list[4:12]

['D', 'A', 'T', 'A', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [249]:
my_list # Ekleme

['D', 'A', 'T', 'A', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [250]:
my_list.insert(4, " & ")
my_list

['D', 'A', 'T', 'A', ' & ', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [251]:
len(my_list)

13

In [252]:
my_list = [1,2,3,[10,20,30],4,(10,20,30)]

In [253]:
# my_list_plus = [1,2,3,[10,20,[1,2,3,[10,20,30],4,1,2,3,[10,20,30],4]],4]

In [254]:
my_list[3]

[10, 20, 30]

In [255]:
my_list[3][2]

30

In [256]:
my_list[3][2]

30

In [257]:
my_list[2:]

[3, [10, 20, 30], 4, (10, 20, 30)]

In [258]:
my_list[4:]

[4, (10, 20, 30)]

In [259]:
my_list = ["D","A","T","A"," ","S","C","I","E","N","C","E"]

In [260]:
"-".join(my_list)

'D-A-T-A- -S-C-I-E-N-C-E'

In [261]:
date = ["25","09","2022"]
"/".join(date)

'25/09/2022'

In [262]:
my_list.count("A")

2

In [263]:
viki = "Albert Einstein (Almanca telaffuz Tüm zamanların en iyi fizikçilerinden kabul edilen Einstein, en çok görelilik teorisini geliştirmesiyle tanınır."

In [264]:
len(viki)

146

In [265]:
viki_list = viki.split()

In [266]:
viki_list

['Albert',
 'Einstein',
 '(Almanca',
 'telaffuz',
 'Tüm',
 'zamanların',
 'en',
 'iyi',
 'fizikçilerinden',
 'kabul',
 'edilen',
 'Einstein,',
 'en',
 'çok',
 'görelilik',
 'teorisini',
 'geliştirmesiyle',
 'tanınır.']

In [267]:
for u in viki_list:
    print(u, ", uzunlugu ", len(u))

Albert , uzunlugu  6
Einstein , uzunlugu  8
(Almanca , uzunlugu  8
telaffuz , uzunlugu  8
Tüm , uzunlugu  3
zamanların , uzunlugu  10
en , uzunlugu  2
iyi , uzunlugu  3
fizikçilerinden , uzunlugu  15
kabul , uzunlugu  5
edilen , uzunlugu  6
Einstein, , uzunlugu  9
en , uzunlugu  2
çok , uzunlugu  3
görelilik , uzunlugu  9
teorisini , uzunlugu  9
geliştirmesiyle , uzunlugu  15
tanınır. , uzunlugu  8


In [268]:
viki_list

['Albert',
 'Einstein',
 '(Almanca',
 'telaffuz',
 'Tüm',
 'zamanların',
 'en',
 'iyi',
 'fizikçilerinden',
 'kabul',
 'edilen',
 'Einstein,',
 'en',
 'çok',
 'görelilik',
 'teorisini',
 'geliştirmesiyle',
 'tanınır.']

In [269]:
for u in viki_list:
    print(u.upper(),":",len(u))

ALBERT : 6
EINSTEIN : 8
(ALMANCA : 8
TELAFFUZ : 8
TÜM : 3
ZAMANLARIN : 10
EN : 2
IYI : 3
FIZIKÇILERINDEN : 15
KABUL : 5
EDILEN : 6
EINSTEIN, : 9
EN : 2
ÇOK : 3
GÖRELILIK : 9
TEORISINI : 9
GELIŞTIRMESIYLE : 15
TANINIR. : 8


In [270]:
viki_list[0]

'Albert'

In [271]:
viki_list[0].count("e")

1

In [272]:
viki.count("e")

15

## SECTION : FOR

In [273]:
# ben bir n'im.. listede gezerim. Her turda bir sayiyi tasirim

In [274]:
for num in [3,4,40]:
    print("veri:",num)
    a = num*num
    print("karesi :",a)
    print("...")

veri: 3
karesi : 9
...
veri: 4
karesi : 16
...
veri: 40
karesi : 1600
...


In [275]:
for num in [3,4,40]:
    print("veri:",num)
    a = num*num
    print("karesi :",a)
print("...")

veri: 3
karesi : 9
veri: 4
karesi : 16
veri: 40
karesi : 1600
...


In [276]:
for u in [3,4,40]:
    print(u)

3
4
40


In [277]:
for a in [3,4,40]:
    print(a*a)

9
16
1600


In [278]:
for u in [3,4,40]:
    print(u)
    a = u*u
    print(a)
    print("----")

3
9
----
4
16
----
40
1600
----


In [279]:
for a in [3,4,40,14]:
    a = a+1
    print(a)

4
5
41
15


In [280]:
for u in ["Age","Gender","Income","City"]:
    a = u.upper() + "_cat"
    print(a)

AGE_cat
GENDER_cat
INCOME_cat
CITY_cat


In [281]:
a

'CITY_cat'

In [282]:
a=0

for d in [3,4,40]:
    print(a)
    a = a + d


0
3
7


In [283]:
a=0

for d in [3,4,40]:
  a = a + d

print(a)

47


In [284]:
range(0, 10)

range(0, 10)

In [285]:
for u in range(0, 100,10):
    print(u*u)

0
100
400
900
1600
2500
3600
4900
6400
8100


In [286]:
a = "miuul"
for u in range(0, 3):
    a=a+a
    print(a)

miuulmiuul
miuulmiuulmiuulmiuul
miuulmiuulmiuulmiuulmiuulmiuulmiuulmiuul


In [287]:
x = range(0, 10,2)

for n in x:
  print(n)

0
2
4
6
8


In [288]:
x = range(0, 10,2)
a=0
for n in x:
  print("su anda a:", a)
  print("su anda n:", n)
  print("---------")
  a =n+3
  print("su anda a:", a)


su anda a: 0
su anda n: 0
---------
su anda a: 3
su anda a: 3
su anda n: 2
---------
su anda a: 5
su anda a: 5
su anda n: 4
---------
su anda a: 7
su anda a: 7
su anda n: 6
---------
su anda a: 9
su anda a: 9
su anda n: 8
---------
su anda a: 11


In [289]:
x = range(0, 10,2)

for n in x:
  print(n)

0
2
4
6
8


In [290]:
for u in range(0, 15,5):
    print(u)

0
5
10


In [291]:
listem = [100]
listem

[100]

In [292]:
listem.insert(1,200)

In [293]:
listem

[100, 200]

In [ ]:
listem = [100]


for u in range(0, 100,5):
    listem.insert(1,listem[0]+u)
    print(listem)

[100, 100]
[100, 105, 100]
[100, 110, 105, 100]
[100, 115, 110, 105, 100]
[100, 120, 115, 110, 105, 100]
[100, 125, 120, 115, 110, 105, 100]
[100, 130, 125, 120, 115, 110, 105, 100]
[100, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 150, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 155, 150, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 160, 155, 150, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 165, 160, 155, 150, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 170, 165, 160, 155, 150, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 175, 170, 165, 160, 155, 150, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 180, 175, 170, 165, 160, 155, 150, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 185, 180, 175, 170, 165, 160, 155, 150, 145, 140, 135, 130, 125, 120, 115, 110, 105, 100]
[100, 190, 185, 180, 175, 170, 165, 1

## SECTION : DATA MANUPLATION - NUMPY

In [294]:
#liste>>array>>data frame

In [295]:
a = [10,20,30,40]
b = [22,23,24,25]

#topla = [32,43,54,65]
a+b

[10, 20, 30, 40, 22, 23, 24, 25]

In [296]:
len(a)

4

In [297]:
b[0]

22

In [298]:
topla =[]
topla.append(a[0]+b[0])
topla.append(a[1]+b[1])
topla.append(a[2]+b[2])
topla.append(a[3]+b[3])
topla

[32, 43, 54, 65]

In [299]:
topla = []

for u in range(0,len(a)):
    topla.append(a[u]+b[u])

topla

[32, 43, 54, 65]

In [300]:
a+b

[10, 20, 30, 40, 22, 23, 24, 25]

In [301]:
# Kapsayici, sirali, degistitilebilir

In [302]:
a = [10,20,30,"ah"]
b = [22,23,24,25]

In [303]:
a+b

[10, 20, 30, 'ah', 22, 23, 24, 25]

In [304]:
# Numerical Python..... Numpy

In [305]:
# beni ekleyin...(import)
# kurallarim var uyun

In [306]:
#Kutuphane Yukleme
import numpy as np

In [307]:
arrayim = np.array([10,20,30,40])

In [308]:
arrayim

array([10, 20, 30, 40])

In [309]:
a = np.array([10,20,30,40])
b = np.array([22,23,24,25])

In [310]:
a+b

array([32, 43, 54, 65])

In [311]:
listem.sum()

AttributeError: 'list' object has no attribute 'sum'

In [312]:
b.sum()

94

In [313]:
# For
# liste>>array...

In [314]:
# Liste & Array

In [315]:
a_liste = [10,20,30,40,4,500,52]
b_liste = [22,23,24,25,8,13,-10]

In [316]:
a_array = np.array([10,20,30,40,4,500,52])
b_array = np.array([22,23,24,25,8,13,-10])

In [317]:
a_liste + b_liste

[10, 20, 30, 40, 4, 500, 52, 22, 23, 24, 25, 8, 13, -10]

In [318]:
a_array + b_array #!!!!!!!!!!

array([ 32,  43,  54,  65,  12, 513,  42])

In [319]:
a_liste<40

TypeError: '<' not supported between instances of 'list' and 'int'

In [320]:
a_array<40

array([ True,  True,  True, False,  True, False, False])

In [321]:
(a_liste<35) | (a_liste>50)

TypeError: '<' not supported between instances of 'list' and 'int'

In [322]:
(a_array<35) | (a_array>50)

array([ True,  True,  True, False,  True,  True,  True])

In [323]:
a_array

array([ 10,  20,  30,  40,   4, 500,  52])

In [324]:
a_array[0]

10

In [325]:
a_array[0:3]

array([10, 20, 30])

In [326]:
(a_array<35) | (a_array>50)

array([ True,  True,  True, False,  True,  True,  True])

In [327]:
a_array[[True,  True,  True, False,  True,  True,  True]]

array([ 10,  20,  30,   4, 500,  52])

In [328]:
a_array[(a_array<35) | (a_array>50)]

array([ 10,  20,  30,   4, 500,  52])

In [329]:
a_array[(a_array<35)]

array([10, 20, 30,  4])

In [330]:
a_array[(a_array>350)]

array([500])

In [331]:
np.array(viki.split())

array(['Albert', 'Einstein', '(Almanca', 'telaffuz', 'Tüm', 'zamanların',
       'en', 'iyi', 'fizikçilerinden', 'kabul', 'edilen', 'Einstein,',
       'en', 'çok', 'görelilik', 'teorisini', 'geliştirmesiyle',
       'tanınır.'], dtype='<U15')

In [332]:
new_array = np.array(viki.split())
new_array

array(['Albert', 'Einstein', '(Almanca', 'telaffuz', 'Tüm', 'zamanların',
       'en', 'iyi', 'fizikçilerinden', 'kabul', 'edilen', 'Einstein,',
       'en', 'çok', 'görelilik', 'teorisini', 'geliştirmesiyle',
       'tanınır.'], dtype='<U15')

In [333]:
np.array(viki.split())=="Albert"

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [334]:
sorgu = np.array(viki.split())=="Albert"

In [335]:
new_array[sorgu]

array(['Albert'], dtype='<U15')

In [360]:
a_array

array([ 10,  20,  30,  40,   4, 500,  52])

In [337]:
a_array.std()

166.5804947299947

In [338]:
a_array.sum()

656

In [339]:
a_array.max()

500

# Homework
* Bu notebook u bilgileri degistirerek tekrar RUN edin
* [1,2,3,4,5,6,7] listesinde dolaşın ve sayilarin karelerinin toplamini veren bir for dongusu yapin
* np.abs, np.sum, np.std, np.append, np.around, np.arange,np.shape,np.reshape fonksiyonlari icin birer ornek yapin

In [390]:
# Let`s make sum of squares of the list [1,2,3,4,5,6,7] 

In [395]:
sum = 0 
for i in [1,2,3,4,5,6,7]:
    sum = i*i + sum
    
print(sum) 

140


In [356]:
a_array

array([ 10,  20,  30,  40,   4, 500,  52])

In [357]:
import numpy as np

In [359]:
np.abs(a_array)

array([ 10,  20,  30,  40,   4, 500,  52])

In [388]:
np.sum(a_array)

656

In [353]:
type(a_array)

numpy.ndarray

In [389]:
np.std(a_array)

166.5804947299947

In [362]:
np.append(a_array,(3,2.7))

array([ 10. ,  20. ,  30. ,  40. ,   4. , 500. ,  52. ,   3. ,   2.7])

In [363]:
np.around(a_array)

array([ 10,  20,  30,  40,   4, 500,  52])

In [384]:
y = np.arange(0,21,4)  #last value is not included
y

array([ 0,  4,  8, 12, 16, 20])

In [385]:
np.shape(y)

(6,)

In [374]:
np.reshape #<function numpy.reshape(a, newshape, order='C')>

<function numpy.reshape(a, newshape, order='C')>

In [386]:
np.reshape(y, (3,2))

array([[ 0,  4],
       [ 8, 12],
       [16, 20]])